### ISSUE TITLE
ReadGroupArgumentCollection should not use GATK AddOrReplaceReadGroups args

### ISSUE THREAD

**Issue by magicDGS** [magicDGS/ReadTools#366]
The `ReadGroupArgumentCollection` class uses GATK's `AddOrReplaceReadGroups` arguments, but this was a port of a picard tool which was removed when GATK changed to import the picard project instead. To update GATK to the 4.0.0.0 release, we should:

- [x] Remove usages from missing class in GATK 4.0.0.0 - until it is updated and picard changed, we should use placeholders in our argument definitions.
- [ ] Port the changes of `AddOrReplaceReadGroups` for the argument names to picard
- [ ] Use the `AddOrReplaceReadGroups` arguments from picard  in our code.

**Comment by magicDGS** [comment]
Move to pending: I should decide if a port to Picard is worth!

**Comment by magicDGS** [comment]
After all the problems that using arguments from Picard/GATK in our toolkit, I decided to do not go in this direction anymore. It is true that GATK was a pre-release when I was using it for ReadTools, but still it might be problematic at some point. Maybe I will come back to the idea later.
