### ISSUE TITLE
Update GATK to released version

### ISSUE THREAD

**Issue by magicDGS** [magicDGS/ReadTools#372]
We should update to GATK 4.0.0.0 without a major bump of ReadTools version. That means that we should check the following:

- [ ] No argument changes in our tools (this can be tested by generating the documentation)
- [ ] Documentation does not change (maybe the addition of some new arguments, but nothing else)
- [ ] Behavior is the same for every tool (all test passing)

**Comment by magicDGS** [comment]
Changes in beta releases that might affect the update (and that can be done in a small basis):

- [ ] Current master (2018/01/25 - `4.beta.5@577c763`) to `4.beta.6`: **minor**
  1. Picard is included (might help fixing #369 and #370 partially)
  2. Minor fixes in ReadFilter HTML documentation (better docs in documentation)
- [ ] `4.beta.6` to `4.beta.6@424bd95`: minor
  1. Picard update and definetly removed duplicated classes
  2. We can extend `BaseTest` for our testing framework to benefit for some methods (not tested nor required)
- [ ] `4.beta.6@424bd95` to `4.beta.6@5f96033`: **major**
  1. Updated Barclay to 1.2.2 changes the argument extension to *.args* instead of *.list*. Maybe no one is aware of this feature anyway and we can change and document if necessary.
  2. Upgrade to htsjdk 2.13.1 (some methods deprecated) and gkl 0.8.2 (maybe problems)
  3. Support multiple libraries in LibraryReadFilter (adds functionality, does not remove)
- [ ] `4.beta.6@5f96033` to `4.beta.6@13bb6e0`: **minor**
  1. Some arguments update to kebab-case in SV code (probably nothing to worry about)
  2. Program group re-organization (important, but only doc effect)
- [ ] `4.beta.6@13bb6e0` to `4.0.0.0`: **incompatible**
  1. Change argument collections and ReadFilter args to kebab-case (completely incompatible)
  2. Owner configuration (requires work on my side for configure properly in ReadTools)
  3. Update to htsjdk 2.13.2 and picard 2.16.0 (no changes required - important for update for us before GATK)
  4. Update Hadoop-BAM to 7.9.1 (no changes)
  5. Other kebab-case changes important and not
  6. Update commons-io to 2.5 (probably no changes)
  7. Update barclay to 2.0.0 - this requires update plugins
  8. Update picard to 2.17.2 - complete changes of program groups
  9. Probably other minor things

**Comment by magicDGS** [comment]
Branch https://github.com/magicDGS/ReadTools/tree/dgs_update_gatk_to_4.0.0.0 contains almost all needed changes (only proof-of-concept, requires more work in some classes). The only problematic breaking change in the current state is the params for `ReadFilters` (and not picked by tests, probably the arguments in `CommandLineProgram`).

In addition, the configuration is still not added to the ReadTools source.

**Comment by magicDGS** [comment]
New progress. If jumping directly from `4.beta.6@13bb6e0` to `4.0.2.1`:

- [ ] `4.0.0.0` to `4.0.1.0`: **minor**
  1. HTSJDK update to 2.14.1
  1. Maybe a `ReadClipper` incompatibility for trimmer (see https://github.com/magicDGS/ReadTools/issues/356)
  1. Can override the read filter arguments thanks to https://github.com/broadinstitute/gatk/commit/033c743402155c0beb25939a952d6c1fe7f62352 (part of #346)
  1. Barclay update (probably no effect)
  1. Disable interval expansion (probably no effect)
- [ ] `4.0.1.0` to `4.0.1.1`: **minor**
  1. Removing junit (can cause unexpected stuff in test if I was not careful - probably we can fix before)
- [ ] `4.0.1.1` to `4.0.1.2`: **minor**
  1. GKL update (might fail in MacOS - test)
- [ ] `4.0.1.2` to `4.0.2.0`: **minor**
  1. Remove Google API (might produce some transitive dependency in use to be removed)
  1. GKL update (might fail in MacOS - test)
  1. HTSJDK update to 2.14.3
- [ ] `4.0.2.0` to `4.0.2.1`: **minor**
  1. Config file is fixed - but not argument
  2. Can override default arguments in CLP thanks to https://github.com/broadinstitute/gatk/commit/15593a3e1960afc36f95925dbf9bdd53df0f50f9 (can solve #364, and part of #346)


This solves everything except the `--config` argument, which does not do anything in ReadTools and I don't want to support...
