### ISSUE TITLE
Create a bundle for ReadTools similar to GATK's one

### ISSUE THREAD

**Issue by magicDGS** [magicDGS/ReadTools#414]
We should generate a bundled zip for the release which includes the following (once it is available):

- [ ] A jar file for running ReadTools locally in the `libexec` folder.
- [ ] A jar file for running ReadTools with Spark/Hadoop (requires #110 and/or #345) in the `libexec` folder
- [ ] A launcher script, more or less complicated, to use with the bundled jar files (requires #318) - it should have a couple of options for running with/without hadoop libraries, etc. This should be in the `bin` folder
- [ ] A bash-completion file (requires #413) - I guess that `etc` is the proper way to place this.

This zip file would be included in every release. This would be helpful for better usability of ReadTools and instalation (e.g., download the zip file, uncompress and use with `~/bin/readtools`). If the whole folder structure is added to the `PATH`, then it can be used out of the box. In addition, it would be easily installed with a hombrew formula without the need of compilation.
